version: '3.8'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  front:
    build:
      context: ./front/web
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - back

  #mobile:
  #  build:
  #    context: .
  #    dockerfile: ./front/Mobile/Dockerfile
  #    args:
  #      EXPO_TOKEN: ${EXPO_TOKEN}
  #      JDK_VERSION: 17.0.12