version: '3.8'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  front:
    build:
      context: ./front/web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - back

  mobile:
    build:
      context: .
      dockerfile: ./front/Mobile/Dockerfile
      args:
        EXPO_TOKEN: ${EXPO_TOKEN}