openapi: 3.0.0
info:
  title: Areas Service API
  version: 1.0.0
  description: API documentation for managing areas, including actions and reactions for users.
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: Areas
    description: Endpoints related to areas management
paths:
  /areasAll:
    get:
      tags:
        - Areas
      summary: Get all areas
      description: Returns a list of all areas.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '500':
          description: Internal server error

  /areas:
    get:
      tags:
        - Areas
      summary: Get areas for the authenticated user
      description: Returns areas linked to the authenticated user.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
    post:
      tags:
        - Areas
      summary: Create a new area
      description: Creates a new area with the specified action and reaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AreaInput'
      responses:
        '200':
          description: Successful creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Area'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /areas/{id}:
    get:
      tags:
        - Areas
      summary: Get specific area details
      description: Returns details of a specific area.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the area
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Area'
        '405':
          description: Area not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Areas
      summary: Delete a specific area
      description: Deletes the specified area along with its actions and reactions.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the area
          schema:
            type: string
      responses:
        '200':
          description: Successful deletion
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Area deleted"
        '401':
          description: Unauthorized
        '405':
          description: Area not found
        '500':
          description: Internal server error

  /areas/{id}/actions:
    get:
      tags:
        - Areas
      summary: Get actions of a specific area
      description: Returns the actions associated with a specific area.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the area
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Action'
        '405':
          description: Area not found
        '500':
          description: Internal server error

  /areas/{id}/reactions:
    get:
      tags:
        - Areas
      summary: Get reactions of a specific area
      description: Returns the reactions associated with a specific area.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the area
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reaction'
        '405':
          description: Area not found
        '500':
          description: Internal server error

  /testAreas:
    get:
      tags:
        - Areas
      summary: Test the areas functionality
      description: Tests the areas service and returns a test message.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Test Areas"
        '500':
          description: Internal server error

components:
  schemas:
    Area:
      type: object
      properties:
        _id:
          type: string
          example: "6727727e5dfbb147ac8badd2"
        title:
          type: string
          example: "test"
        description:
          type: string
          example: "test"
        action:
          type: string
          example: "6727727e5dfbb147ac8badcc"
        reactions:
          type: string
          example: "6727727e5dfbb147ac8badcf"
        update_delay:
          type: integer
          example: 1800
        deleted:
          type: boolean
          example: false
        last_update:
          type: string
          format: date-time
          example: "2024-11-03T12:54:22.375+00:00"
        __v:
          type: integer
          example: 0

    AreaInput:
      type: object
      properties:
        area_title:
          type: string
          example: "New Area"
        area_description:
          type: string
          example: "Description of the new area"
        action_name:
          type: string
          example: "New Action"
        action_description:
          type: string
          example: "Description of the new action"
        action_type:
          type: string
          example: "Type of action"
        action_platform:
          type: string
          example: "Platform of action"
        reaction_name:
          type: string
          example: "New Reaction"
        reaction_description:
          type: string
          example: "Description of the new reaction"
        reaction_type:
          type: string
          example: "Type of reaction"
        reaction_platform:
          type: string
          example: "Platform of reaction"

    Action:
      type: object
      properties:
        _id:
          type: string
          example: "actionId1"
        title:
          type: string
          example: "Action 1"
        description:
          type: string
          example: "Description of Action 1"

    Reaction:
      type: object
      properties:
        _id:
          type: string
          example: "reactionId1"
        title:
          type: string
          example: "Reaction 1"
        description:
          type: string
          example: "Description of Reaction 1"
