openapi: 3.0.0
info:
  title: Tokens Service API
  version: 1.0.0
  description: API documentation for managing user tokens across different platforms.
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /tokens:
    get:
      tags:
        - Tokens
      summary: Get all tokens for the authenticated user
      description: Returns all tokens associated with the authenticated user.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "tokenId1"
                    platform:
                      type: string
                      example: "GitHub"
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
    post:
      tags:
        - Tokens
      summary: Create a new token
      description: Creates a new token for a specified platform.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform:
                  type: string
                  example: "GitHub"
                tokenValue:
                  type: string
                  example: "your-token-value"
      responses:
        "200":
          description: Successful creation
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "tokenId1"
                  platform:
                    type: string
                    example: "GitHub"
        "401":
          description: Unauthorized
        "409":
          description: Token already exists for platform
        "500":
          description: Internal server error

  /tokens/platform/{platform}:
    get:
      tags:
        - Tokens
      summary: Get a token for a specific platform
      description: Returns the token associated with a specific platform.
      parameters:
        - name: platform
          in: path
          required: true
          description: Name of the platform
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "tokenId1"
                  platform:
                    type: string
                    example: "GitHub"
        "401":
          description: Unauthorized
        "405":
          description: User not found
        "406":
          description: Token not found for platform
        "500":
          description: Internal server error
    patch:
      tags:
        - Tokens
      summary: Update a token for a specific platform
      description: Updates the token associated with a specific platform.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tokenValue:
                  type: string
                  example: "new-token-value"
      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "tokenId1"
                  platform:
                    type: string
                    example: "GitHub"
        "401":
          description: Unauthorized
        "405":
          description: User not found
        "406":
          description: Token not found for platform
        "500":
          description: Internal server error
    delete:
      tags:
        - Tokens
      summary: Delete a token for a specific platform
      description: Deletes the token associated with a specific platform.
      parameters:
        - name: platform
          in: path
          required: true
          description: Name of the platform
          schema:
            type: string
      responses:
        "200":
          description: Successful deletion
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Token deleted successfully"
        "401":
          description: Unauthorized
        "405":
          description: User not found
        "406":
          description: Token not found for platform
        "500":
          description: Internal server error

  /tokens/state:
    get:
      tags:
        - Tokens
      summary: Get the state of tokens across platforms
      description: Returns the existence state of tokens for various platforms.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: boolean
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
