name: deploy-web.yml

on:
  push:
    branches:
      - dev

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: ./front/web

      - name: Build Angular project
        run: npm run build -- --configuration production
        working-directory: ./front/web

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.HOME_SERVER_USER }}
          server: ${{ secrets.HOME_SERVER_IP }}
          password: ${{ secrets.HOME_SERVER_PASSWORD }}
          port: 22
          local_path: "./front/web/dist/web/browser/*"
          remote_path: "./home/server/Area"
          sftpArgs: "-o ConnectTimeout=5"

      - name: Restart Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOME_SERVER_IP }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: systemctl restart apache2
