name: deploy-web.yml

on:
  push:
    branches:
      - dev

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: ./front/web

      - name: Build Angular project
        run: npm run build -- --configuration production
        working-directory: ./front/web

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOME_SERVER_IP }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./front/web/dist/web/browser/*"
          target: "/home/server/Area"

      - name: Restart Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOME_SERVER_IP }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: systemctl restart apache2
